### ISSUE TITLE
aaa

### ISSUE THREAD

**Issue by MargauxLou** [ACNestor/projecttwo#1]
Hola

**Comment by ACNestor** [comment]
Hola qué ase, ya entiendo el problema que planteas. Por cierto, acepto pull requests (e invitaciones a comer). Sobre el problema que comentas: me puedes dar más información? De momento sólo veo "Hola".

Gracias!

**Comment by ACNestor** [comment]
Aaaah, ya creo que sé por dónde vas. Probemos añadiendo al código "import numpy as np".
Gracias por ayudarme a mejorar mi código.

**Comment by ACNestor** [comment]
También puedes borrar import ojete as ogt y aaaaaaaaaa, creo que no aportan mucho ; )

**Comment by ACNestor** [comment]
Cierro la issue pq se ha arreglado con la pull request que me has enviado y he aceptado. Gracias!
